name: ulima
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  barcode_widget: ^2.0.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/LOGOAPP.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/Universidad_de_Lima_logo.png
    - assets/images/foto.jpeg
  fonts:
    - family: Calibri
      fonts:
        - asset: assets/fonts/calibri-regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
